config/routes.rb
DmProject::Application.routes.draw do
  get '/', to: redirect('/binning')
  get '/binning', to: 'main#binning'
  post '/binning', to: 'main#binning_generate'

  get '/clustering', to: 'main#clustering'
  post '/clustering', to: 'main#clustering_generate'

  get '/algorithms', to: 'main#algorithms'
  get '/about', to: 'main#about'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
require 'rinruby'

class MainController < ApplicationController

  @@r=RinRuby.new(:echo=>false)
  @@categories = [
    ["ALIMENTARY TRACT AND METABOLISM", :A],
    ["BLOOD AND BLOOD FORMING ORGANS", :B],
    ["CARDIOVASCULAR SYSTEM", :C],
    ["DERMATOLOGICALS", :D],
    ["GENITO URINARY SYSTEM AND SEX HORMONES", :G],
    ["SYSTEMIC HORMONAL PREPARATIONS, EXCL. SEX HORMONES AND INSULINS", :H],
    ["ANTIINFECTIVES FOR SYSTEMIC USE", :J],
    ["ANTINEOPLASTIC AND IMMUNOMODULATING AGENTS", :L],
    ["MUSCULO-SKELETAL SYSTEM", :M],
    ["NERVOUS SYSTEM", :N],
    ["ANTIPARASITIC PRODUCTS, INSECTICIDES AND REPELLENTS", :P],
    ["RESPIRATORY SYSTEM", :R],
    ["SENSORY ORGANS", :S],
    ["VARIOUS", :V]
  ]

  def binning
    @show_pictures = false
    set_binning
  end

  def binning_generate
    @show_pictures = true
    set_binning
    @@r.eval "setwd('#{Dir.pwd}')"
    @@r.bins = @bins.to_i
    @@r.lag = @lag.to_i
    @@r.param = (@weather_param.split(' ')).join('.')
    @@r.medicine_group = @medicine_group
    @@r.time_unit = @time_unit
    file = (params[:binning] == 'equal-freq' ? 'R/equal-freq.R' : 'R/equal-width.R')
    @@r.eval File.read(file)
    render 'binning'
  end

  def clustering
    @show_pictures = false
    set_clustering
  end

  def clustering_generate
    set_clustering
    flash[:message] = nil
    @show_pictures = true
    if (@weather_param.blank? || @weather_param.empty?)
      @show_pictures = false
      flash[:message] = "Choose weather parameter"
    else
      @@r.eval "setwd('#{Dir.pwd}')"
      @@r.k = @clusters.to_i
      @@r.alpha = @alpha
      @@r.minPts = @minPts
      @@r.time_unit = @time_unit
      @@r.clusteringColumns = @weather_param.map{|p, v| p}
      @@r.medicine_group = @medicine_group
      @@r.clustering_name = @clustering
      @@r.eval File.read('R/Project.R')
    end
    render 'clustering'
  end

  def about
  end

  def algorithms
  end

private
  def set_clustering
    session['weather_param'] = @weather_param = params['weather_param']
    session['clusters'] = @clusters = params['clusters'] || 4
    session['medicine_group'] = @medicine_group = params['medicine_group'] || :A
    session['clustering'] = @clustering = params['clustering'] || "kmeans"
    session['time_unit'] = @time_unit = params['time_unit'] || "week"
    session['alpha'] = @alpha = params['alpha'] || 0.2
    session['minPts'] = @minPts = params['minPts'] || 5
    @medicine_family = []
    @medicine_family << File.read("data/medicine_family1.txt").split("\n").map{|record| record.split("\t")}
    @medicine_family << File.read("data/medicine_family2.txt").split("\n").map{|record| record.split("\t")}
    @medicine_family << File.read("data/medicine_family3.txt").split("\n").map{|record| record.split("\t")}
    @medicine_family << File.read("data/medicine_family4.txt").split("\n").map{|record| record.split("\t")}
    @categories = @@categories
  end

  def set_binning
    session['weather_param'] = @weather_param = params['weather_param'] || "Temperature"
    session['bins'] = @bins = params['bins'] || 4
    session['lag'] = @lag = params['lag'] || 1
    session['time_unit'] = @time_unit = params['time_unit'] || "week"
    session['binning'] = @binning = params['binning'] || "equal-freq"
    session['medicine_group'] = @medicine_group = params['medicine_group'] || :A
    @medicine_family = []
    @medicine_family << File.read("data/medicine_family1.txt").split("\n").map{|record| record.split("\t")}
    @medicine_family << File.read("data/medicine_family2.txt").split("\n").map{|record| record.split("\t")}
    @medicine_family << File.read("data/medicine_family3.txt").split("\n").map{|record| record.split("\t")}
    @medicine_family << File.read("data/medicine_family4.txt").split("\n").map{|record| record.split("\t")}
    @categories = @@categories
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Data Mining Project</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag    "bootstrap", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "bootstrap", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body>
<div class="container marg-cont">

    <%= yield %>
</div>

</body>
</html>

app/views/main/about.html.erb
<ul class="nav nav-pills top-menu" role="menu">
  <li><a href="/binning">Binning</a></li>
  <li><a href="/clustering">Clustering</a></li>
  <li><a href="/algorithms">Algorithms</a></li>
  <li class="active"><a href="#">About</a></li>
</ul>


<div class="page-header">
  <h1>About</h1>
</div>
<%= image_tag "clustering.png", {height: 300} %>


app/views/main/algorithms.html.erb
<ul class="nav nav-pills top-menu" role="menu">
  <li><a href="/binning">Binning</a></li>
  <li><a href="/clustering">Clustering</a></li>
  <li class="active"><a href="#">Algorithms</a></li>
  <li><a href="/about">About</a></li>
</ul>


<div class="page-header">
  <h1>Algorithms description</h1>
</div>

app/views/main/binning.html.erb
<ul class="nav nav-pills top-menu" role="menu">
  <li><a href="#">Binning</a></li>
  <li><a href="/clustering">Clustering</a></li>
  <li><a href="/algorithms">Algorithms</a></li>
  <li><a href="/about">About</a></li>
</ul>

<div class="page-header">
  <h1>Binning</h1>
</div>

<div class="tab-content">
    <%= form_tag(binning_path) do %>
    <table id="params" class="table">
      <tr>
        <td>
          <h3>Choose number of bins</h3>
          <%= text_field_tag :bins, @bins %><br/>

          <h3>Choose medicines group</h3>
          <%= select_tag(:medicine_group, options_for_select(@categories, :selected => @medicine_group), :class => 'form-control') %>


          <h3>Binning method</h3>
          <%= radio_button_tag(:binning, "equal-width", (@binning=="equal-width")) %>
          <label for="binning_equal-width">Equal Width</label><br/>
          <%= radio_button_tag(:binning, "equal-freq", (@binning=="equal-freq")) %>
          <label for="binning_equal-freq">Equal frequency</label>

          <h3>Time unit</h3>
          <%= radio_button_tag(:time_unit, "day", (@time_unit=="day")) %>
          <label for="time_unit_day">Day</label><br/>
          <%= radio_button_tag(:time_unit, "week", (@time_unit=="week")) %>
          <label for="time_unit_week">Week</label><br/>
          <%= radio_button_tag(:time_unit, "month", (@time_unit=="month")) %>
          <label for="time_unit_month">Month</label>


          <h3>Lag</h3>
          <%= text_field_tag :lag, @lag %><br/>

        </td>
        <td>
          <h3>Choose the arguments for clustering</h3>
          <table id="weather" class="table table-striped">
            <tr>
              <td><%= radio_button_tag(:weather_param, "Temperature", (@weather_param=="Temperature")) %>
                <label for="weather_param_temperature">Temperature</label></td>
            </tr>
            <tr>
              <td><%= radio_button_tag(:weather_param, "Humidity", (@weather_param=="Humidity")) %>
                <label for="weather_param_humidity">Humidity</label></td>
            </tr>
            <tr>
              <td><%= radio_button_tag(:weather_param, "Air pressure", (@weather_param=="Air pressure")) %>
                <label for="weather_param_air_pressure">Air pressure</label></td>
            </tr>
            <tr>
              <td><%= radio_button_tag(:weather_param, "Wind speed", (@weather_param=="Wind speed")) %>
                <label for="weather_param_wind_speed">Wind speed</label></td>
            </tr>
            <tr>
              <td><%= radio_button_tag(:weather_param, "Precipitation", (@weather_param=="Precipitation")) %>
                <label for="weather_param_precipitation">Precipitation</label></td>
            </tr>
            <tr>
              <td><%= radio_button_tag(:weather_param, "UV index", (@weather_param=="UV index")) %>
                <label for="weather_param_uv_index">UV index</label></td>
            </tr>
            <tr>
              <td><%= radio_button_tag(:weather_param, "Light", (@weather_param=="Light")) %>
                <label for="weather_param_light">Light</label></td>
            </tr>
            <tr>
              <td><%= radio_button_tag(:weather_param, "Irradiation flux", (@weather_param=="Irradiation flux")) %>
                <label for="weather_param_irradiation_flux">Irradiation flux</label></td>
            </tr>
            <tr>
              <td><%= radio_button_tag(:weather_param, "Gamma radiation", (@weather_param=="Gamma radiation")) %>
                <label for="weather_param_gamma_radiation">Gamma radiation</label></td>
            </tr>

          </table>
        </td>
      </tr>
    </table>
    <%= submit_tag("Generate") %>
  <% end %>

  <% if @show_pictures %>
      <% for i in [1,2,3,4] %>
          <div id="chart-div">
            <%= image_tag "family#{i}.png", {width: 1000} %>
            <table class="table">
            <% for medicine in @medicine_family[i-1] %>
                <tr>
                  <td>
                    <%= link_to "#{medicine[0]}", "http://www.whocc.no/atc_ddd_index/?code=#{medicine[0]}", :class => 'btn btn-primary' %>
                  </td>
                  <td>
                    <%= medicine[1] %>
                  </td>
                </tr>
            <% end %>
            </table>
          </div>
      <% end %>
  <% end %>

</div>

app/views/main/clustering.html.erb
<ul class="nav nav-pills top-menu" role="menu">
  <li><a href="/binning">Binning</a></li>
  <li><a href="/#">Clustering</a></li>
  <li><a href="/algorithms">Algorithms</a></li>
  <li><a href="/about">About</a></li>
</ul>

<div class="page-header">
  <h1>Clustering</h1>
</div>
<h3 style="display:inline-block; background:rgba(255,0,0,0.1); color:red;"><%= flash[:message] %></h3>
<div class="tab-content">
  <%= form_tag do %>
      <table id="params" class="table">
        <tr>
          <td>

            <h3>Choose medicines group</h3>
            <%= select_tag(:medicine_group, options_for_select(@categories, :selected => @medicine_group), :class => 'form-control') %>

            <h3>Clustering method</h3>
            <table class="table">
              <tr>
                <td>
                  <%= radio_button_tag(:clustering, "kmeans", (@clustering=="kmeans")) %>
                  <label for="binning_equal-width">K-means</label>
                </td>
                <td>


                  <%= label_tag 'clusters', 'Number of clusters' %> <br/>
                  <%= text_field_tag :clusters, @clusters %><br/>

                </td>
              </tr>
              <tr>
                <td>
                  <%= radio_button_tag(:clustering, "dbscan", (@clustering=="dbscan")) %>
                  <label for="binning_equal-freq">DBscan</label>
                </td>
                <td>
                  <%= label_tag 'alpha', 'Alpha' %> <br/>
                  <%= text_field_tag :alpha, @alpha %><br/>
                  <%= label_tag 'minPts', 'min PTS' %> <br/>
                  <%= text_field_tag :minPts, @minPts %>

                </td>
              </tr>
              <tr>
                <td>
                  <h3>Time unit</h3>
                  <%= radio_button_tag(:time_unit, "day", (@time_unit=="day")) %>
                  <label for="time_unit_day">Day</label><br/>
                  <%= radio_button_tag(:time_unit, "week", (@time_unit=="week")) %>
                  <label for="time_unit_week">Week</label><br/>
                  <%= radio_button_tag(:time_unit, "month", (@time_unit=="month")) %>
                  <label for="time_unit_month">Month</label>
                </td>
              </tr>
            </table>


          </td>
          <td>
            <h3>Choose the arguments for clustering</h3>
            <table id="weather" class="table table-striped">
              <tr>
                <td><%= check_box_tag("weather_param[Temperature]") %>
                  <label for="weather_param_temperature">Temperature</label></td>
              </tr>
              <tr>
                <td><%= check_box_tag("weather_param[Humidity]") %>
                  <label for="weather_param_humidity">Humidity</label></td>
              </tr>
              <tr>
                <td><%= check_box_tag("weather_param[Air.pressure]") %>
                  <label for="weather_param_air_pressure">Air pressure</label></td>
              </tr>
              <tr>
                <td><%= check_box_tag("weather_param[Wind.speed]") %>
                  <label for="weather_param_wind_speed">Wind speed</label></td>
              </tr>
              <tr>
                <td><%= check_box_tag("weather_param[Precipitation]") %>
                  <label for="weather_param_precipitation">Precipitation</label></td>
              </tr>
              <tr>
                <td><%= check_box_tag("weather_param[UV.index]") %>
                  <label for="weather_param_uv_index">UV index</label></td>
              </tr>
              <tr>
                <td><%= check_box_tag("weather_param[Light]") %>
                  <label for="weather_param_light">Light</label></td>
              </tr>
              <tr>
                <td><%= check_box_tag("weather_param[Irradiation.flux]") %>
                  <label for="weather_param_irradiation_flux">Irradiation flux</label></td>
              </tr>
              <tr>
                <td><%= check_box_tag("weather_param[Gamma.radiation]") %>
                  <label for="weather_param_gamma_radiation">Gamma radiation</label></td>
              </tr>

            </table>
          </td>
        </tr>
      </table>
      <%= submit_tag("Generate") %>
  <% end %>

  <% if @show_pictures %>
      <% for i in [1,2,3,4] %>
          <div id="chart-div">
            <%= image_tag "family#{i}.png", {width: 1000} %>
            <table class="table">
              <% for medicine in @medicine_family[i-1] %>
                  <tr>
                    <td>
                      <%= link_to "#{medicine[0]}", "http://www.whocc.no/atc_ddd_index/?code=#{medicine[0]}", :class => 'btn btn-primary' %>
                    </td>
                    <td>
                      <%= medicine[1] %>
                    </td>
                  </tr>
              <% end %>
            </table>
          </div>
      <% end %>
  <% end %>

</div>

app/views/main/index.html.erb
<ul class="nav nav-pills top-menu" role="menu">
  <li class="active"><a href="/binning">Home</a></li>
  <li><a href="/algorithms">Algorithms</a></li>
  <li><a href="/about">About</a></li>
</ul>

<div class="page-header">
  <h1>Main</h1>
</div>

<ul class="nav nav-tabs" id="tabs">
  <li class="active"><a href="#clustering" data-toggle="tab">Clustering</a></li>
  <li><a href="#binning" data-toggle="tab">Binning</a></li>
</ul>

<div class="tab-content">
  <div class="tab-pane active" id="clustering">

    <table id="params">
      <tr>
        <td>
          <h3>Choose clustering method</h3>
          <select id="clustering">
            <option value="kmeans">K-means</option>
            <option value="som">SOM</option>
          </select>

          <h3>Choose medicines group</h3>

          <select id="medicine">
            <option value="1">Nervous system</option>
            <option value="2">Antibiotics</option>
          </select>
        </td>
        <td>
          <h3>Choose the arguments for clustering</h3>
          <table id="weather">
            <tr>
              <td><input type="checkbox" value="Temperature"> Temperature</td>
            </tr>
            <tr>
              <td><input type="checkbox" value="Humidity">Humidity</td>
            </tr>
            <tr>
              <td><input type="checkbox" value="Air pressure">Air pressure</td>
            </tr>
            <tr>
              <td><input type="checkbox" value="Wind speed">Wind speed</td>
            </tr>
            <tr>
              <td><input type="checkbox" value="Precipitation">Precipitation</td>
            </tr>
            <tr>
              <td><input type="checkbox" value="UV index">UV index</td>
            </tr>
            <tr>
              <td><input type="checkbox" value="Light">Light</td>
            </tr>
            <tr>
              <td><input type="checkbox" value="Irradiation">Irradiation flux</td>
            </tr>
            <tr>
              <td><input type="checkbox" value="Gamma radiation">Gamma radiation</td>
            </tr>

          </table>
        </td>
      </tr>
    </table>
  </div>

  <%= @res %>

  <div id="chart-div">
    <%= image_tag "img.png", {width: 1000} %>
  </div>


  <script type="text/javascript">

  $(document).ready(function(){
       //root = $("#chart-div")
       //img = $('<img src="assets/images/img.png">')
       //root.append(img)
      /*var invoked = window.invoked;
      if(invoked === undefined){
          window.invoked = true;
      } else {
          return
      }
      width = 500
      data = <%= @data %>
      n = data.length

      var vis = new pv.Panel()
              .width(500)
              .height(250)
              .canvas(document.getElementById('chart-div'));

      vis.add(pv.Rule)
              .data(pv.range(0, 2, .2))
              .bottom(pv.range(0, 2, .2))
              .add(pv.Label);

      bar_width = width/n
      vis.add(pv.Bar)
              .data(data)
              .width(bar_width * 0.9)
              .height(function(d) d * 250)
      .bottom(0)
              .left(function() this.index * bar_width)
      .anchor("bottom").add(pv.Label);

      vis.render();*/
  })
</script>

</div>
  <div class="tab-pane" id="binning">...</div>
</div>